### ISSUE TITLE
AP Demo text opening error 

### ISSUE THREAD

**Issue by hannahroseeli** [inpho/topic-explorer#107]
After running the demo and opening the topic explorer, click the button that will select a random document at the 40 topic model. Then, go to the left of the document bar and click on the icon of the AP logo. The error occurs here, because nothing will happen.

**Comment by colinallen** [comment]
Replicated on my laptop too.


On Feb 18, 2016, at 12:04 PM, hannahroseeli <notifications@github.com<mailto:notifications@github.com>> wrote:


After running the demo and opening the topic explorer, click the button that will select a random document at the 40 topic model. Then, go to the left of the document bar and click on the icon of the AP logo. The error occurs here, because nothing will happen.
