### ISSUE TITLE
Add config option to change number of words displayed in browser.

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#109]

**Comment by colinallen** [comment]
I’m trying to tweak server.py to show 25 words in the topic tooltips when the words are Chinese characters.  

Currently the number of words is hard coded by the :10 here:

    for i,topic in enumerate(data):
        js[str(i)].update({'words' : dict([(w, p) for w,p in topic[:10]])})

Obviously, I could hard code something else, but I thought the better way to do it would be to try to read a lang = cn line from the config .ini file and use it to test. But if I add that line to the config file and I try something like:
	if config.get(“main”,”lang”)==‘cn': wordmax = 25
the topic explorer just hangs with “Rendering chart” in the first bar.  It loads fine when I set wordmax = 25 without the if clause, or using True there, so obviously there’s something I’m not understanding about config.get.

In the main block of server.py I see
config = ConfigParser({
        'certfile' : None,
        'keyfile' : None,
        'ca_certs' : None,
	...

followed by lines such as:
    path = config.get('main', 'path')

So I thought I could just copy that syntax, and use lang = config.get(‘main’,’lang’) there in main and test lang==‘cn’ in the conditional, but that also causes the browser to hang while rendering the chart.  (1==1 works fine, so it’s not the fact of a test.)

Next thought was that maybe the problem is with trying to get the value of lang within the topics() function which is under  @route('/topics.json’) not main. But when I try calling ConfigParser() there, it runs that line but the server dies before launching, logging the error ConfigParser.NoSectionError: No section: ‘main’.

This leads me to realize I don’t understand how ConfigParser works, even in the main section, because I don’t see any reference to the name of the config .ini file anywhere in server.py.  (The argument passed to ConfigParser is just a set of key : value pairs.)

**Comment by colinallen** [comment]
Problem solved -- I had accidentally deleted  config.read(args.config) in main, which is of course where the ini file is identified.  Will push changes to chinese branch shortly.
