### ISSUE TITLE
ini file is created relative to modeled dir, not pwd

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#128]
The following image illustrates an issue with model directory and .ini file placement

![image](https://cloud.githubusercontent.com/assets/666240/16030500/963a52a4-31bf-11e6-89e6-59b7793d2f72.png)

**Comment by colinallen** [comment]
Maybe the following raises a bunch of separate issues, but it is a chance to rethink a bit the way that ini files, models, notebooks, logs, and the raw documents are organized and named relative to one another. (See also the issue #129 I just opened on fulltext links.)  

It’s fairly common to have a working directory containing multiple corpora, and when one models those, the ini files are kept straight by the assigned corpus name, but some elements have name clashes — e.g. the corpus.py file for each Corpus will collide in the notebooks directory. Maybe there should be notebooks/Corpus subdirectories, or Corpus/notebooks for each Corpus.  Similarly, maybe ini files should not be generated in the directory from which vsm is run, but put into Corpus/config.  (Similarly for Corpus/logs, etc.)  

Another problem, with a large hierarchically structured Corpus, such as Handian, one sometimes wants to model all of it, but sometimes one wants to model just one of the subdirectories.  I’ve tried two approaches — 
(1) Create a symlink at the top level to the corpus subdirectory several levels down.  This partly works, but init puts the initial corpus file one level up from wherever the symlink points, which is not where it needs to be, which then causes problems for prep.
(2) Run prep directly in the relevant subfolder, but this creates a problem when modeling the whole corpus because all the files generated for the submodel are assumed to be data for the full model.

**Comment by JaimieMurdock** [comment]
I've also noticed some issues when working with PDF corpora - sometimes the
ini files point to the '-txt' folder and sometimes to the raw folder.
