### ISSUE TITLE
term search in Chinese

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#138]
Chinese users will want to enter multiple words such as "尽信书" but the lack of spacing means that this will cause an error, so we need to detect Chinese term search input and introduce vertical bars to effectively search for http://inphodata.cogs.indiana.edu/handian/60/?q=%E5%B0%BD|%E4%BF%A1|%E4%B9%A6 instead of http://inphodata.cogs.indiana.edu/handian/60/?q=%E5%B0%BD%E4%BF%A1%E4%B9%A6

**Comment by JaimieMurdock** [comment]
This now needs to transfer to the cluster view, but the bug is still valid and needs to be set.

Proposed solution: add the tokenization method to the .ini file and use that to parse all query terms. This will also solve an issue with the SKOS tokenizers.

**Comment by JaimieMurdock** [comment]
This issue involves a few different things:

*Default execution* 
The search on clusters runs from the `/topics` cluster page. You type a list of words and it queries the topic models using the `/topics.json` endpoint, which is in `topicexplorer.server.word_topic_distance` (line 362 in current master).

An example of this request is: https://www.hypershelf.org/sep/topics.json?q=health+care

It splits the search in the `q` parameter on the `' '` or `'|'` characters. In URLs, the `+` is decoded to ` ` automatically, so the example is looking up `['health', 'care']`.

The function also filters the search terms to only those words that actually appear in our corpus object. Since we do stoplisting, this means that ultra-frequent terms might not occur: `the` or in the Stanford Encyclopedia's case `philosophy`.

*Problem* 
In Chinese, there are no delimiters between "words" - that is, no spaces. Our corpus has words though because we use the tokenizer `topicexplorer.lib.chinese.ancient_chinese_tokenizer`. 

This could be a problem for other tokenizers too: for example, we have an experimental inpho tokenizer that will match terms like `artificial intelligence` to their corresponding terms in the InPhO ontology like this `inpho:2203`: https://www.inphoproject.org/taxonomy/2203

In order to fix that, we want to be able to reuse the same tokenizer in `topicexplorer.server.word_topic_distance` if a special one is used.

In `topicexplorer.init` we select a tokenizer using the flag here: https://github.com/inpho/topic-explorer/blob/master/topicexplorer/init.py#L152

In order to do this we need to have three steps:
1. The `init` stage needs to save the `tokenizer` that was used so it can be reimported later in the `serve` stage. This could either be done by saving the full path to the module used (i.e., `topicexplorer.lib.chinese.ancient_chinese_tokenizer`) or by just saving `args.tokenizer` in the `write_config` file (easier, path of least resistance).
2. In `topicexplorer.server` we need to add access to that `tokenizer` config variable on the `Application` object:
  - add a new argument in `__init__`: `tokenizer='default'`
  - parse the config file in `create_app` for the `tokenizer` value we established in step 1, and send that onto the Application consturctor. Code will likely go here-ish: https://github.com/inpho/topic-explorer/blob/master/topicexplorer/server.py#L750
3. In the `word_topic_distance` function, do a check on the tokenizer before handling the `request.query.q` variable. If not `default`, then pass `request.query.q` to the right tokenizer. If not, do the default handling. that's there already. Either way at the end, you end up with the list of tokens in the `query` variable, so something like `query = tokenizer(request.query.q)` will appear in that code somewhere.
