### ISSUE TITLE
symlinks cause init to fail

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#176]
when trying to init a corpus through a symbolic link to directory correct number of file etc. is detected, but invalid path message is returned (e.g. H1 is symbolic link below).  Should test for symlinks and either say it's not supported or handle appropriately.

Corpus Name [Default: H1] 
Building corpus from H1 4695 files, 341 dirs, 0 levels
with coll_corpus function
ERROR: invalid path, please specify either:
  * a single plain-text or PDF file,
  * a single bibtex (.bib) file with 'file' fields,
  * a folder of plain-text or PDF files, or
  * a folder of folders of plain-text or PDF files.

Exiting...

**Comment by JaimieMurdock** [comment]
This is a really intense bug. To test it I ran `topicexplorer demo` then symlinked the `ap` dir from `/tmp/ap`. when I ran `topicexplorer init` it somehow found the `ap.ini` and tried to retrain the models, which were messed up because it was running from `/tmp`.

I suspect there's an `abspath` vs. `relpath` inconsistency that at least partially explains this.

**Comment by JaimieMurdock** [comment]
I've got a fix in issues/176 branch that passes all tests, however I'm not sure how robust it is to `import`/`export`

**Comment by colinallen** [comment]
How should I test import/export functionality?

**Comment by JaimieMurdock** [comment]
I just got it tested, about to merge.

```
mkdir ~/ap-demo
cd ~/ap-demo
topicexplorer demo
cd /tmp
ln -s ~/workspace/inpho/topic-explorer/ap/ ap
topicexplorer init ap
topicexplorer prep ap --high-percent 50 --low-percent 5 --lang en -q
topicexplorer train ap
topicexplorer export ap
mkdir /tmp/test
cd /tmp/test
topicexplorer import /tmp/ap.tez
```
