### ISSUE TITLE
"Module could not be found" while installing on Windows

### ISSUE THREAD

**Issue by bricksdont** [inpho/topic-explorer#247]
I'm running into a problem while installing the topicexplorer package on Windows.

Steps and Specs:

- Windows 10, 64bit
- Downloaded and installed Miniconda 64bit for Python 2, added Anaconda to the PATH
- in Powershell, type `pip install topicexplorer`

```sh
[truncated, here is the last line of the pip command:]
Successfully installed topicexplorer-1.0b192
PS C:\Users\ZB-user> topicexplorer version
```
```python
Traceback (most recent call last):
  File "c:\users\zb-user\miniconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\zb-user\miniconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\ZB-user\Miniconda2\Scripts\topicexplorer.exe\__main__.py", line 5, in <module>
  File "c:\users\zb-user\miniconda2\lib\site-packages\topicexplorer\__main__.py", line 31, in <module>
    from topicexplorer import (init, prep, train, server, notebook,
  File "c:\users\zb-user\miniconda2\lib\site-packages\topicexplorer\notebook.py", line 16, in <module>
    import topicexplorer.lib.win32
  File "c:\users\zb-user\miniconda2\lib\site-packages\topicexplorer\lib\win32.py", line 31, in <module>
    ctypes.CDLL(numpy_libmmd)
  File "c:\users\zb-user\miniconda2\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```

I also tried a developer install that is mentioned [here](https://pypi.python.org/pypi/topicexplorer) for example, but this error remains.

What do I have to change to make it work?

Thanks!

**Comment by JaimieMurdock** [comment]
The error seems to be in one of the DLL loads for numpy. I won't have a chance to debug until this evening.

If you are comfortable editing files, a quick workaround may be to comment out line 16 in `c:\users\zb-user\miniconda2\lib\site-packages\topicexplorer\notebook.py`
```
    # import topicexplorer.lib.win32
```

**Comment by bricksdont** [comment]
Thanks,
I'm not in a rush but I'll try commenting out the import.

Let me know if you need more info from me to reproduce this error.

**Comment by bricksdont** [comment]
By the way, only commenting it out does not work, either the `if` statement must also be commented out or adding a `pass` works.

**Comment by JaimieMurdock** [comment]
Finally getting a cycle to review.

This code is part of a module that only loads during the notebook execution. It is intended to capture Ctrl+C events which are overridden by an event handler in `scipy.stats`. I'm currently looking at the effects of removing this module altogether.

In the process I discovered that `ujson` is missing from the conda env, which is part of why the appveyor builds are struggling.

More to come.

**Comment by JaimieMurdock** [comment]
`topicexplorer.lib.win32` was originally introduced as a fix for #76.

**Comment by JaimieMurdock** [comment]
Re-reading the install instructions here, it seems that Miniconda could be the root of the problems. This module is looking for numpy binaries. It's not finding them during the setup process because I don't have it listed as a dependency in `setup.py`. I suspect there are other hidden dependencies not listed in setup.py that I was relying on Anaconda (full-version) to install.

**Comment by JaimieMurdock** [comment]
I disabled `topicexplorer.lib.win32`
- With `topicexplorer notebook` and no active kernel, Ctrl+C still works properly.
- With an active kernel and `vsm.spatial` imported, Ctrl+C breaks due to the `scipy.stats` issue.

In order to avoid a regression of #76, `topicexplorer.lib.win32` will live on.

However, to do the permanent fix, I'll be updating the dependencies in `setup.py` and looking into packaging a conda environment and alternate install instructions with Miniconda so @bricksdont's issue doesn't happen again. I can understand the need for not installing a ~560MB package just to get a single app working 👍

**Comment by bricksdont** [comment]
Thanks for getting back to me on this!

For clarity: does this mean that I can try to reinstall on Windows as soon as you update the dependencies?

**Comment by JaimieMurdock** [comment]
I just pushed a release to pypi, and also updated the README to show the proper dependencies for miniconda:

`conda install numpy scipy scikit-learn nltk matplotplib ipython networkx unidecode wget decorator chardet ujson requests notebook`

then run:
`pip install topicexplorer==1.0b196`
