### ISSUE TITLE
Unexpected Removing of Special Chars

### ISSUE THREAD

**Issue by oguzhanalasehir** [inpho/topic-explorer#323]
Hi,

Although I do not apply "topicexplorer prep" step for my dataset, it somehow excludes special characters such as underscore ( _ ) in init, train or notebook steps. Could you please let me know how to overcome this issue?

My topicexplorer version is 1.0b216-0-g5306f26

Best regards,

**Comment by colinallen** [comment]
Punctuation stripping and word tokenization happens in  https://github.com/inpho/vsm/blob/master/vsm/extensions/corpusbuilders/util.py -- you'll see some custom punctuation stripping beginning line 21, and the the default for word tokenization is NLTK's Penn Treebank Word Tokenizer which we deploy around line 186 (see http://www.nltk.org/_modules/nltk/tokenize/treebank.html for documentation of that).  

It is also possible to deploy different tokenizers, as we have done for Chinese (https://github.com/inpho/topic-explorer/blob/master/topicexplorer/lib/chinese.py, using a customized punctuation list.

**Comment by oguzhanalasehir** [comment]
Thanks.
Can u help me about which part of the code should be changed for my purpose. My aim is basically just preventing removal of underscore ( _ ) characters in my corpus.

Sorry, I am not so familiar with codes. That's why I need your extra help

Best regards,

**Comment by JaimieMurdock** [comment]
Hi @oguzhanalasehir, I just pushed a change to the master branch that includes a simplified tokenizer.

I think you have a developer install, right? If you do a `topicexplorer update` or `git pull` you should see these changes as long as your version is greater than `1.0b216-11`.

The code for a simple tokenizer is in [topicexplorer/tokenizer/__init__.py](https://github.com/inpho/topic-explorer/blob/master/topicexplorer/tokenizer/__init__.py). In order to use it, change the way you run `topicexplorer init YOUR_FILES` to:
```
topicexplorer init --tokenizer simple YOUR_FILES
```

I made this one without `_` characters being removed just to demo.

**Comment by JaimieMurdock** [comment]
Closing issue.
